### ISSUE TITLE
README command

### ISSUE THREAD

**Issue by ericladage** [mxstbr/karabiner#1]
This is great stuff! just fyi - backticks in launch step are messing with markdown, could change to:

```
``launchctl kickstart -k gui/`id -u`/org.pqrs.karabiner.karabiner_console_user_server``
```

**Comment by mxstbr** [comment]
Ah, thank you for letting me know!

**Comment by mxstbr** [comment]
Fixed! https://github.com/mxstbr/karabiner/commit/a37c672a3fe7a488640194891136a2c8ae35db95
