### ISSUE TITLE
Question: Interaction with Rectangle

### ISSUE THREAD

**Issue by kaspersoerensen** [mxstbr/karabiner#14]
First off - man this is nice! Saves me a lot of time and makes the config much simpler!

I only have one problem that I can't seem to figure out: How to interact with Rectangle. I can see that you have implemented this already, but I cannot get it to work. Rectangle is installed and I can just the regular shortcuts to manipulate the windows. But I cannot get it to work using your script. The Logs in Rectangle and Karabiner-Elements do not give me any good clues about what is going on. 

Any good advise about where to go from here? 

/Kasper

**Comment by mxstbr** [comment]
I recently (5 days ago) changed how Karabiner interacts with Rectangle in https://github.com/mxstbr/karabiner/commit/ca458bb1293e1bb82ec180bc7e917c19943d84e0. Before, it would rely on Rectangle's keyboard shortcuts being present. After, it uses Rectangle's `open` URL commands to trigger the window movement even if no keyboard shortcuts are set/they are different from the defaults.

Can you check:

1. Which version of this repository are you on? Is it before or after this commit?
2. Which version of Rectangle are you on? I'm on `v0.76`.

**Comment by kaspersoerensen** [comment]
Hi Max, thank you very much for the reply.

I am on the latest commit of your script and version v0.76 (82) of Rectangle. 

I just tried to insert the line `"shell_command": "open -g 'rectangle://execute-action?name=left-half'"` directly into the `karabiner.json` - that does work, so I am now pretty sure it has something to do with the Mac I was testing on before (Running MacOS 13), that is not functioning correctly, and not your code.

**Comment by mxstbr** [comment]
Got it. Thanks for debugging. I'll close this issue for now; let me know if it does turn out to be an issue with the code here and we'll keep debugging.

**Comment by JDuffe** [comment]
Hi Max, 
I kind of have a follow-up question to the one above: I've looked through your config files and was wondering why some actions are executed through the Rectangle URL and some as normal keyboard shortcuts. 
Does Rectangle not support every action through URLs, or is there no particular reason for this implementation?

**Comment by mxstbr** [comment]
I don't recall; most likely I just forgot to update them to the URLs!
