### ISSUE TITLE
👍 Running Raycast extension action on background without popup

### ISSUE THREAD

**Issue by sluzhynskyi** [mxstbr/karabiner#19]
Hi 
I really liked your idea and I want to bring some small lifehack.
So there is some deeplinks that you are opening with Raycast but it opens Raycast popup-> does the action -> closes popup. But it would be better to not show popup and just do the action. 
So for that, just add to the end of the raycast deeplink **?launchType=background**

For example I added shortcuts for Spotify Raycast extension:
```
c: {
  p: open("raycast://extensions/mattisssa/spotify-player/togglePlayPause?launchType=background"),
  n: open("raycast://extensions/mattisssa/spotify-player/next?launchType=background"),
  b: open("raycast://extensions/mattisssa/spotify-player/previous?launchType=background"),
},
```

and also I have separate shortcut for pause/resume foreground media, so in this way you can stop Spotify even if you are watching some video with shortcut.

[Manual](https://developers.raycast.com/information/lifecycle/deeplinks) from Raycast docs.

Thanks for your repo and last video with guy from the Raycast🥳

**Comment by mxstbr** [comment]
Thanks for the tip, this is awesome! 👍
