### ISSUE TITLE
Add Mouse Pointer with Hyper + a (arrow pointer)+ {hjkl}

### ISSUE THREAD

**Issue by NationAdel** [mxstbr/karabiner#3]
Hi,
It would be nice to add the mouse pointer movement to a sublayer.
Add Mouse Pointer with Hyper + a (arrow pointer)+ {hjkl}

I don't know if the mouse (up/down/left/right)(speed)/scroll up, variables are set

found mouse keys are just integers.
thanks

**Comment by mxstbr** [comment]
I'd love to see your solution for this! I tried adding a mouse layer, but it felt unnatural to use to me.
